before_script:
    - export PATH=$PATH:bin/
    - export DISPLAY=:99
    - export TMPDIR=tmp/
stages:
    - test
    - robot
test_operun:
    stage: test
    script:
        # Build
        - /usr/bin/virtualenv .
        - ./bin/pip install -r requirements.txt
        - ./bin/buildout -c develop.cfg -t 3 -v
        # Test
        - ./bin/coverage erase
        - ./bin/coverage run -p --source=src bin/test || exit 1
        - ./bin/coverage combine
        - ./bin/coverage html
        - ./bin/coverage report
robot_operun:
    stage: test
    script:
        # Build
        - /usr/bin/virtualenv .
        - ./bin/pip install -r requirements.txt
        - ./bin/buildout -c develop.cfg -t 3 -v
        # Robot
        - ./bin/test --all -t robot
